Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,7 +1,8 @@
 name: Build
-
 on:
   workflow_dispatch:
+  schedule:
+    - cron: '0 0 * * *'
 
 concurrency:
   group: build
@@ -20,13 +21,69 @@ jobs:
       packages: write
       contents: read
     steps:
+      - 
+        name: Run graphql query to get tag
+        uses: octokit/graphql-action@v3.x
+        id: latest_tag
+        with:
+          variables: |
+            repo: ZimaOS
+            owner: IceWhaleTech
+          query: |
+            query tag($owner: String!, $repo: String!) {
+              repository(owner: $owner, name: $repo) {
+                refs(refPrefix: "refs/tags/", last: 1, orderBy: {field: TAG_COMMIT_DATE, direction: ASC}) {
+                  edges {
+                    node {
+                      name
+               } } } } }
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - 
+        name: Parse tag from query output
+        run: |
+          #!/bin/bash
+          latest_tag=$(echo '${{ steps.latest_tag.outputs.data }}' | jq '.repository.refs.edges[][].name' -r)
+          [ -z "$latest_tag" ] && echo "Tag not found!" && exit 1
+          [[ "$latest_tag" == "null" ]] && echo "Tag not found!" && exit 1
+          [[ "$latest_tag" = v* ]] && latest_tag="${latest_tag:1}"
+          echo "Found tag: \"${latest_tag}\"" 
+          latest_version="${latest_tag%-*}"
+          major="${latest_version%%.*}"
+          minor="${latest_version#*.}"
+          minor="${minor%%.*}"
+          echo "latest_tag=$latest_tag" >> $GITHUB_ENV
+          echo "latest_minor=$major.$minor" >> $GITHUB_ENV
+      - 
+        name: Check if the tag exists locally
+        uses: action-pack/tag-exists@v1
+        id: checkTag
+        with: 
+          tag: 'v${{ env.latest_tag }}'
+      -
+        name: Finish when found
+        run: |
+          #!/bin/bash
+          beta="false"
+          
+          val="${{ steps.checkTag.outputs.exists }}"
+
+          [[ "${{ env.latest_tag }}" == *"rc"* ]] && beta="true"
+          [[ "${{ env.latest_tag }}" == *"beta"* ]] && beta="true"
+          [[ "${{ env.latest_tag }}" == *"test"* ]] && val="true"
+          [[ "${{ env.latest_tag }}" == *"alpha"* ]] && val="true"
+
+          echo "beta=${beta}" >> $GITHUB_ENV
+          echo "exists=${val}" >> $GITHUB_ENV
       -
         name: Checkout
+        if: env.exists == 'false'
         uses: actions/checkout@v6
         with:
           fetch-depth: 0
       -
         name: Docker metadata
+        if: env.exists == 'false'
         id: meta
         uses: docker/metadata-action@v6
         with:
@@ -35,23 +92,27 @@ jobs:
             ${{ secrets.DOCKERHUB_REPO }}
             ghcr.io/${{ github.repository }}
           tags: |
-            type=raw,value=latest,priority=100
-            type=raw,value=${{ vars.MAJOR }}.${{ vars.MINOR }}
+            type=raw,value=${{ env.latest_minor }},enable=${{ env.beta == 'false' }}
+            type=raw,value=latest,priority=100,enable=${{ env.beta == 'false' }}
+            type=raw,value=${{ env.latest_tag }},priority=250
           labels: |
             org.opencontainers.image.title=${{ vars.NAME }}
         env:
-          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest
+          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index     
       - 
         name: Set up Docker Buildx
+        if: env.exists == 'false'
         uses: docker/setup-buildx-action@v4
       -
         name: Login into Docker Hub
+        if: env.exists == 'false'
         uses: docker/login-action@v4
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}
       -
         name: Login to GitHub Container Registry
+        if: env.exists == 'false'
         uses: docker/login-action@v4
         with:
           registry: ghcr.io
@@ -59,12 +120,13 @@ jobs:
           password: ${{ secrets.GITHUB_TOKEN }}
       -
         name: Build Docker image
+        if: env.exists == 'false'
         uses: docker/build-push-action@v7
         with:
           context: .
           push: true
           provenance: false
-          platforms: linux/amd64
+          platforms: linux/amd64,linux/arm64
           tags: ${{ steps.meta.outputs.tags }}
           labels: ${{ steps.meta.outputs.labels }}
           annotations: ${{ steps.meta.outputs.annotations }}
@@ -72,18 +134,15 @@ jobs:
             VERSION_ARG=${{ steps.meta.outputs.version }}
       -
         name: Create a release
+        if: env.exists == 'false'
         uses: action-pack/github-release@v2
         with:
           tag: "v${{ steps.meta.outputs.version }}"
           title: "v${{ steps.meta.outputs.version }}"
           token: ${{ secrets.REPO_ACCESS_TOKEN }}
       -
-        name: Increment version variable
-        uses: action-pack/bump@v2
-        with:
-          token: ${{ secrets.REPO_ACCESS_TOKEN }}
-      -
         name: Send mail
+        if: env.exists == 'false'
         uses: action-pack/send-mail@v1
         with:
           to: ${{secrets.MAILTO}}
